name: Lint & Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CONTAINER_NAME: test-container

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            **/setup.cfg
      - name: Lint
        run: |
          make develop
          make lint
  test:
    if: always()
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            **/setup.cfg
      - name: Local Test
        run: |
          make develop
          make coverage
  docker-test:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: |
            **/setup.cfg
      - name: Docker Test
        run: |
          docker buildx build -f Docker/test/Dockerfile -t ${{ env.CONTAINER_NAME }}:${{ github.sha }} .
          docker run --rm --entrypoint "/bin/sh" ${{ env.CONTAINER_NAME }}:${{ github.sha }} -c "make test"
